on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: run test
      run: make tests
      working-directory: ./testing
© 2020 GitHub, Inc.
